# Site settings
title: Jimmy's Blog
email: visperc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Record life
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://visperc.github.io" # the base hostname & protocol for your site
twitter_username: Jimmy
github_username:  visperc

# Build settings
markdown: kramdown
